- name: Desplegar backend de ChatWeb
  hosts: web
  become: true
  vars_files:
    - ../group_vars/web.yml

  tasks:
    - name: Instalar dependencias del sistema
      apt:
        name:
          - curl
          - nodejs
          - npm
        state: present
        update_cache: yes
      #when: not skip_install

    - name: Instalar PM2 globalmente
      npm:
        name: pm2
        global: yes
      #when: not skip_install

    - name: Instalar dependencias del backend
      command: npm install
      args:
        chdir: "{{ BACKEND_DIR }}"

    - name: Verificar si el proceso PM2 ya existe
      command: pm2 list
      register: pm2_output
      changed_when: false
      failed_when: false

    - name: Reiniciar backend si ya está corriendo
      command: pm2 restart "{{ APP_NAME }}"
      when: "'{{ APP_NAME }}' in pm2_output.stdout"
      args:
        chdir: "{{ BACKEND_DIR }}"
      ignore_errors: true

    - name: Iniciar backend con PM2 si no está corriendo
      command: pm2 start src/index.js --name "{{ APP_NAME }}"
      when: "'{{ APP_NAME }}' not in pm2_output.stdout"
      args:
        chdir: "{{ BACKEND_DIR }}"

    - name: Guardar configuración de PM2
      command: pm2 save
